import io
import typing as t

class RestreamedBytesIO(object):
    substream: io.BytesIO | None
    encoder: t.Callable[[bytes], bytes]
    encoderunit: int
    decoder: t.Callable[[bytes], bytes]
    decoderunit: int
    rbuffer: bytes
    wbuffer: bytes
    sincereadwritten: int
    def __init__(
        self,
        substream: io.BytesIO | None,
        decoder: t.Callable[[bytes], bytes],
        decoderunit: int,
        encoder: t.Callable[[bytes], bytes],
        encoderunit: int,
    ) -> None: ...
    def read(self, count: int | None = ...) -> bytes: ...
    def write(self, data: bytes | bytearray | memoryview) -> int: ...
    def close(self) -> None: ...
    def seek(self, at: int, whence: int = ...) -> int: ...
    def seekable(self) -> bool: ...
    def tell(self) -> int: ...
    def tellable(self) -> bool: ...

class RebufferedBytesIO(object):
    substream: io.BytesIO | None
    offset: int
    rwbuffer: bytes
    moved: int
    tailcutoff: int | None
    def __init__(
        self, substream: io.BytesIO | None, tailcutoff: int | None = ...
    ) -> None: ...
    def read(self, count: int | None = ...) -> bytes: ...
    def write(self, data: bytes | bytearray | memoryview) -> int: ...
    def seek(self, at: int, whence: int = ...) -> int: ...
    def seekable(self) -> bool: ...
    def tell(self) -> int: ...
    def tellable(self) -> bool: ...
    def cachedfrom(self) -> int: ...
    def cachedto(self) -> int: ...
